language: R
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      env: R_CODECOV=true REDUX_TEST_USE_REDIS=true REDUX_TEST_USE_REDIS_ISOLATED=true
    - os: osx
      osx_image: xcode8.3
      brew_packages: hiredis
      latex: false

addons:
  apt:
    packages:
      - libapparmor-dev
      - libhiredis-dev
      - redis-server

services:
  - redis-server
